# Generated by Django 6.0.6 on 2026-06-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_pedido_total_producto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Detalle_pedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
