# Generated by Django 6.0.6 on 2026-06-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_pedido_cliente_delete_detalle_pedido_and_more'),
        ('pedidos', '0002_alter_pedido_cliente_carrito_item_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
