# Generated by Django 6.0.6 on 2026-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_delete_cliente'),
        ('pedidos', '0002_alter_pedido_cliente_carrito_item_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='detalle_pedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_producto_por_pedido'),
        ),
    ]
