# Generated by Django 6.0.6 on 2026-06-15 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_perfil'),
        ('pedidos', '0003_carrito_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.cliente'),
        ),
    ]
