# Generated by Django 6.0.6 on 2026-06-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_detalle_pedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_carrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='item_carrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Item_carrito',
        ),
    ]
