# Generated by Django 6.0.6 on 2026-06-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_item_carrito_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
