# Generated by Django 6.0.6 on 2026-06-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('pedidos', '0006_alter_detalle_pedido_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='checkout.checkout'),
        ),
    ]
