# Generated by Django 6.0.6 on 2026-07-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
