# Generated by Django 6.0.6 on 2026-07-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_observaciones_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='Costo de envio estándar para este departamento.', max_digits=10),
        ),
    ]
