# Generated by Django 6.0.6 on 2026-06-14 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=20)),
                ('municipio', models.CharField(choices=[('Pereira', 'Pereira'), ('Dosquebradas', 'Dosquebradas'), ('Santa Rosa', 'Santa Rosa'), ('Belalcazar', 'Belalcazar'), ('Belen de Umbria', 'Belen de Umbria'), ('Virginia', 'Virginia'), ('Marsella', 'Marsella')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
