# Generated by Django 6.0.6 on 2026-06-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='municipio',
        ),
    ]
